### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by stock97** [nexus7420/management#1]
Lots of lags when using main camera. Sometimes it force closes and needs a reboot. 3rd party cameras like WhatsApp are working well and smooth like stock rom.

LineageOS 14.1, 22-03-2017 Build
G920F w/ stock kernel

**Comment by Lukas0610** [comment]
We are already aware of this issue, but currently there's no solution to that problem

**Comment by Lukas0610** [comment]
Stock-Camera got removed and was replaced by HTC-Camera by default
