### ISSUE TITLE
Web Server is down

### ISSUE THREAD

**Issue by janwendt** [nexus7420/management#10]
This issue is not related to any of the repositories here but your Web Server (http://nexus7420.cf) has been unavailable for several days.

**Comment by Lukas0610** [comment]
We'll probably publish a updated build again which will be hosted on my server (not the server on which nexus7420.cf is). But @corewell should take a look at this

**Comment by janwendt** [comment]
I tried to download the edge kernel but it is only hosted on nexus7420.cf
