### ISSUE TITLE
Fingerprint unlock works with screen off

### ISSUE THREAD

**Issue by mikep-13** [nexus7420/management#11]
<bug>
Whenever I turn off the screen, I could still turn it back on with fingerprint.

LineageOS Build 02/04
G920T, Stock Kernel

**Comment by Lukas0610** [comment]
This behavior is expected as this is the best way to fix the problem that the fingerprint-scanner randomly stops working.

**Comment by Serkan-devel** [comment]
Could there be a --restart=always implementation like on docker?

**Comment by J0SH1X** [comment]
It's supposed to work like that!!! Every device with fprint and lineage has it
