### ISSUE TITLE
Ability to open apps along with actions with long press or double press hardware keys

### ISSUE THREAD

**Issue by mikep-13** [nexus7420/management#12]
<Feature>

I'd like to see the ability to choose to open an app rather than just being able to only select certain actions when I double press a key, just like Resurrection Remix. That'd be useful so I could open the Google Camera app by double pressing the home button.

**Comment by Lukas0610** [comment]
Sorry, but you should contact LineageOS for such features as we just maintain the generic hardware- and software-functions for the S6
