### ISSUE TITLE
Music playing does not resume when phone call ends

### ISSUE THREAD

**Issue by davidrough** [nexus7420/management#23]
When listening to music and call comes through on phone the music playing does not resume when phone call ends

Listen to music (problem observed using Spotify) , receive call, end call, music should resume as it does on Samsung ROM

SM-G920F with Lineage 02042017 build

**Comment by Usaamah99** [comment]
Samsung ROM is not LineageOS

**Comment by davidrough** [comment]
Please read carefully before posting: "..music should resume **as it does** on Samsung ROM"

Otherwise last line:  "SM-G920F with Lineage 02042017 build"
