### ISSUE TITLE
Third party cameras don't detect all 16MP

### ISSUE THREAD

**Issue by mikep-13** [nexus7420/management#24]
#bug
Some camera don't detect all 16 mp, such as Google Camera version 3 and up. Any fix for this? I'd like to keep the phone fully Google for the most part.
-
LineageOS Build 02/04
G920T, Stock Kernel

**Comment by mikep-13** [comment]
How do I add a tag by the way? I've been trying to figure it out for a bit.

**Comment by Lukas0610** [comment]
We had many problems with the camera-apps except the HTC Camera, which is the reason why we delivery it with the ROM from now on. We can look into it if you could send us some logcats if you open the camera and make a picture.

You can add tags on the sidebar by clicking on the cog right to "Labels"

**Comment by mikep-13** [comment]
[Log_2017-04-08_14-20-08.txt](https://github.com/nexus7420/management/files/907811/Log_2017-04-08_14-20-08.txt)
![screenshot_20170408-142111](https://cloud.githubusercontent.com/assets/26862546/24832552/1b1d2130-1c67-11e7-88b4-bcac7db98d85.png)
![screenshot_20170408-142032](https://cloud.githubusercontent.com/assets/26862546/24832558/299902a6-1c67-11e7-8abe-e18a3cf36ec7.png)

Top screenshot shows Google Camera v 2.7.010
Bottom shows v 4.3.016

**Comment by Lukas0610** [comment]
Probably bug in the app, tested with HTC Camera and Google Camera on latest build
