### ISSUE TITLE
<bug> fingerprint..etc

### ISSUE THREAD

**Issue by ple2man** [nexus7420/management#25]
now i use SM-G920K, version 0402(latest)

fingerprint is always activatied.
when you turn off the screen? what ever, just running scan.

then sometimes, when i turn on the screen, scanner doesn't read my fingerprint. i mean, scanner CANT read anything.

and more bug.
battery is still not good at. its fast going down.
frame drop (maybe throttling...)
some game is not output grahpic.
not coming notice at right time sometime.(maybe excess dozemode)

but yea. this is good rom. i use this rom from initial build.
nice hard work! developer! 
sorry for my bad english!

**Comment by mikep-13** [comment]
Fingerprint is activated when screen is off because it's apparently the best way to fix the bugs of it not working sometimes or having it activating while in the UI

**Comment by ple2man** [comment]
i see thanks! but i think it is needed update.
and battery fast falldown is using data cellular
in other(wifi or bluetooth or both off) is not test yet.

i will test that and add this thread.

**Comment by Usaamah99** [comment]
Fingerprint Working when the screen is off is a default LineageOS Feature. This is not an issue
