### ISSUE TITLE
Youtube 1080p 60fps stuttering

### ISSUE THREAD

**Issue by sir-earl** [nexus7420/management#36]
Video is stuttering in the YouTube app for 1080p 60fps video.

Device: SM-G925I
Build: 2017/04/08

**Comment by Lukas0610** [comment]
Tested in a newer, internal build, could not reproduce it

**Comment by sir-earl** [comment]
Still occurring in 2017/04/14 build.

See for example: https://youtu.be/QzVGf-K2heg

When testing, make sure you have switched to 1080p under quality settings.
