### ISSUE TITLE
Hardware buttons vibrate with screen off

### ISSUE THREAD

**Issue by sir-earl** [nexus7420/management#38]
Hardware buttons vibrate when screen is turned off. This is annoying when phone is in pocket, as they are constantly triggered.

Build: 2017/04/08
Device: SM-G925I

**Comment by Mrtenz** [comment]
Same problem here on a SM-G925F.

**Comment by sir-earl** [comment]
Workaround is to disable "Sounds -> Other sounds -> Vibrate on tap". Unfortunately you will also loose the tactile feedback with the hardware buttons altogether.

**Comment by Lukas0610** [comment]
Fixed by https://github.com/nexus7420/android_device_samsung_zero-common/commit/5130823bea63f53cb982262194984c3cbff4b1de
