### ISSUE TITLE
Camera stops working

### ISSUE THREAD

**Issue by sir-earl** [nexus7420/management#39]
Camera and flash randomly stop working. Opening camera app subsequently shows a black screen, followed by the app silently closing.

A reboot is required to fix the issue.

Happens both with and without using the HTC Camera app linked in the XDA post.

Device: SM-G925I
Build: 2017/04/08

**Comment by sir-earl** [comment]
Logs attached

[2017-04-11_22.57.zip](https://github.com/nexus7420/management/files/912937/2017-04-11_22.57.zip)

**Comment by EnricoSignore** [comment]
same on new lineage and rr...camera is not stable yet
