### ISSUE TITLE
<Critical> Sim Card Not Detect/Found

### ISSUE THREAD

**Issue by NeutrinoBR** [nexus7420/management#43]
[modem.txt](https://github.com/nexus7420/management/files/923649/modem.txt)
[dmesg.txt](https://github.com/nexus7420/management/files/923650/dmesg.txt)
[event.txt](https://github.com/nexus7420/management/files/923652/event.txt)
[last_kmsg.txt](https://github.com/nexus7420/management/files/923651/last_kmsg.txt)
[logcat.txt](https://github.com/nexus7420/management/files/923653/logcat.txt)
In the past compilation the signal had interruptions. Now, it does not even work anymore.

SM-G920I
LineageOS Build 14/04 - Fresh Install
Stock kernel

**Comment by Lukas0610** [comment]
Try to restart the device

**Comment by NeutrinoBR** [comment]
Sorry for not sending the logs. Updated...

I've restarted and already removed the chip.

**Comment by Usaamah99** [comment]
Are you using an MM or N modem?
What stock FW were you on before you flashed LineageOS?

**Comment by NeutrinoBR** [comment]
G920-Modem-4DPJN, i think.

**Comment by Lukas0610** [comment]
Which Android-Version did you use before? Android 5 or 6?

**Comment by NeutrinoBR** [comment]
MM. 6.0.1
(http://www.samsunggalaxyrom.com/2017/03/update-firmware-samsung-galaxy-s6-sm-g920i-g920idvs3eqc1-marshmallow.html)

**Comment by NeutrinoBR** [comment]
Modem: PhoneG920IDVU3EPL1 CONFIRMED!

**Comment by janwendt** [comment]
I have the same issue on my SM-G925F. Moreover when I try to go to "more" in the network settings the settings application crashes.
