### ISSUE TITLE
FingerPrint not always working

### ISSUE THREAD

**Issue by dartoumi** [nexus7420/management#48]
The fingerprint scanner is not always working. When I press the home button and hold my finger on the button it does nothing. This happens sometimes

SM-G920F
Version: 14.04.2017
Kernel: 3.10.61-G920FXXU5EQBG-gfd7258c5ece root@home #1

**Comment by Usaamah99** [comment]
You probably need to enter your PIN instead then.

**Comment by Serkan-devel** [comment]
@dartoumi does the fingerprint scanner still not always work?

**Comment by dartoumi** [comment]
@Serkan-devel it's not as intuitive as stock. Sometimes I have to move my finger little left, right etc until it does something. It's really random. Soms of the time it does work though.
