### ISSUE TITLE
Fast Charging

### ISSUE THREAD

**Issue by dartoumi** [nexus7420/management#5]
## Checklist, delete it if you are finished
 - [ ] Problem exactly described?
 - [ ] Described how to reproduce the problem (If possible)
 - [ ] Other useful informations (Background tasks, open apps, etc.)
 - [ ] Used phone-variant
 - [ ] Used build

### Exactly describe your problem/your request:
...

### If issue, used phone-variant (SM-G920F, SM-G925F, etc.)
...

### If issue, used build (22/03, build-date of kernel)
...

**Comment by Lukas0610** [comment]
Please use the template to give us further informations. Closed.
