### ISSUE TITLE
Build 20170423: Whatsapp Microphone Problem

### ISSUE THREAD

**Issue by janwendt** [nexus7420/management#52]
In Whatsapp calls or audios my voice sounds like a robot. In other apps (Snapchat) there are no problems.

Build: 20170423
Type: zeroltexx (Edge)

**Comment by rogeriollacerda** [comment]
+1 

Build: 20170414
Type: zerofltexx (Flat)

**Comment by Usaamah99** [comment]
Yep we are aware of this.

**Comment by janwendt** [comment]
@Usaamah99 Is it fixed in the next build?
