### ISSUE TITLE
min Call-Volume way to high build 22.3.17

### ISSUE THREAD

**Issue by morbloe** [nexus7420/management#7]
the volume of the internal speaker (not Speaker-Mode) is way to high. In quite environments the caller can hear himself because of the volume.

**Comment by Lukas0610** [comment]
This is a known problem of LineageOS itself. We can't do much to solve that problem.

**Comment by J0SH1X** [comment]
@Lukas0610 it's not lineage problem on my LG g4 i dont have this iusse
